name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Run Deploy Script file
        working-directory: ./
        run: chmod +x ./deploy.sh

     